# Generated by Django 4.2.3 on 2023-12-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_back', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
