# Generated by Django 4.2.3 on 2024-01-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_back', '0002_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Torg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('shipper', models.CharField(max_length=128)),
                ('adress', models.CharField(max_length=128)),
                ('requisites', models.CharField(max_length=128)),
                ('phone', models.IntegerField()),
                ('ocpd', models.IntegerField()),
                ('data', models.DateField()),
                ('pact', models.IntegerField()),
                ('payer', models.ManyToManyField(to='crm_back.payer')),
                ('provider', models.ManyToManyField(to='crm_back.provider')),
            ],
        ),
    ]
