# Generated by Django 4.2.3 on 2024-01-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_back', '0004_drip_espresso_integrale_regular_speciale_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(help_text='Введите вес: ')),
                ('price', models.IntegerField(help_text='Введите сумму')),
                ('name', models.CharField(help_text='Введите название: ', max_length=64)),
                ('description', models.TextField(help_text='Введите описапние: ', max_length=256)),
                ('unit', models.CharField(choices=[('Regular', 'RG'), ('Speciale', 'Sc'), ('Integrale', 'Ig'), ('Espresso', 'Es')], help_text='Выберете сорт: ', max_length=9)),
            ],
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.DeleteModel(
            name='Drip',
        ),
        migrations.DeleteModel(
            name='Espresso',
        ),
        migrations.DeleteModel(
            name='Integrale',
        ),
        migrations.DeleteModel(
            name='Regular',
        ),
        migrations.DeleteModel(
            name='Speciale',
        ),
    ]
