# Generated by Django 4.2.3 on 2024-01-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_back', '0005_new_unit_delete_catalog_delete_drip_delete_espresso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_unit',
            name='unit',
            field=models.CharField(choices=[('RG', 'Regular'), ('SC', 'Speciale'), ('IG', 'Integrale'), ('ES', 'Espresso')], help_text='Выберете сорт: ', max_length=9),
        ),
    ]
