# Generated by Django 4.2.3 on 2024-01-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_back', '0006_alter_new_unit_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_unit',
            name='unit',
            field=models.CharField(choices=[('RG', 'Regular'), ('SC', 'Speciale'), ('IG', 'Integrale'), ('ES', 'Espresso'), ('DR', 'Drip')], help_text='Выберете сорт: ', max_length=9),
        ),
    ]
