# Generated by Django 4.2.3 on 2024-01-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_back', '0008_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(help_text='Введите вес: ')),
                ('mass', models.CharField(choices=[('Kilogramms', 'Kg'), ('Gramms', 'Gr')], help_text='Выберете сорт: ', max_length=64)),
                ('price', models.IntegerField(help_text='Введите сумму')),
                ('name', models.CharField(help_text='Введите название: ', max_length=64)),
                ('description', models.TextField(help_text='Введите описапние: ', max_length=256)),
                ('unit', models.CharField(choices=[('RG', 'Regular'), ('SC', 'Speciale'), ('IG', 'Integrale'), ('ES', 'Espresso'), ('DR', 'Drip')], help_text='Выберете сорт: ', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Opt_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('manager', models.CharField(max_length=64)),
                ('data_created', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='New_Unit',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='torg',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='torg',
            name='provider',
        ),
        migrations.DeleteModel(
            name='Payer',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.DeleteModel(
            name='Torg',
        ),
    ]
