# Generated by Django 4.2.3 on 2024-01-31 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_back', '0011_alter_order_first_name_alter_order_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(help_text='Введите имя', max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(help_text='Введите фамилию', max_length=64, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_catalog',
            field=models.ForeignKey(help_text='Выберете товар', on_delete=django.db.models.deletion.CASCADE, to='crm_back.catalog', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('NEW', 'Новый заказ'), ('WAIT_PAID', 'Ждут отплаты'), ('STARTED', 'В работе'), ('READY', 'Отгружен')], help_text='Выберете статус:', max_length=10, verbose_name='Статус'),
        ),
    ]
