# Generated by Django 4.2.3 on 2024-01-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_back', '0012_alter_order_first_name_alter_order_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.TextField(help_text='Введите описапние: ', max_length=256, unique=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='mass',
            field=models.CharField(choices=[('Kilogramms', 'Кг'), ('Gramms', 'Гр')], help_text='Выберете массу: ', max_length=64, unique=True, verbose_name='Масса'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(help_text='Введите название: ', max_length=64, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='price',
            field=models.IntegerField(help_text='Введите сумму: ', unique=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='unit',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('SCPECIALE', 'Speciale'), ('INTEGRALE', 'Integrale'), ('ESPRESSO', 'Espresso'), ('DRIP', 'Drip')], help_text='Выберете сорт: ', max_length=9, unique=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='weight',
            field=models.IntegerField(help_text='Введите вес: ', unique=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(help_text='Введите имя', max_length=64, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(help_text='Введите фамилию', max_length=64, unique=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('NEW', 'Новый заказ'), ('WAIT_PAID', 'Ждут отплаты'), ('STARTED', 'В работе'), ('READY', 'Отгружен')], help_text='Выберете статус:', max_length=10, unique=True, verbose_name='Статус'),
        ),
    ]
