# Generated by Django 4.2.3 on 2024-01-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_back', '0013_alter_catalog_description_alter_catalog_mass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('NEW', 'Новый заказ'), ('WAIT_PAID', 'Ждут отплаты'), ('STARTED', 'В работе'), ('READY', 'Отгружен')], help_text='Выберете статус:', max_length=10, verbose_name='Статус'),
        ),
    ]
