# Generated by Django 4.2.3 on 2024-02-02 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_back', '0014_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_back.catalog', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('NEW', 'Новый заказ'), ('WAIT_PAID', 'Ждут отплаты'), ('STARTED', 'В работе'), ('READY', 'Отгружен')], max_length=10, verbose_name='Статус'),
        ),
    ]
